CREATE TABLE Journal
	(
	id int NOT NULL,
	ts timestamp NOT NULL,
	message varchar(50) NULL
	)  ON [PRIMARY]
GO

ALTER TABLE Journal ADD CONSTRAINT
	PK_Journal PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE Journal SET (LOCK_ESCALATION = TABLE)
GO