CREATE TABLE JOURNAL_PARAMETER
(
  PARAMETER_ID NUMBER(20) NOT NULL 
, PARAM_NO NUMBER(20) NOT NULL 
, PARAM_VALUE VARCHAR2(200) 
, CONSTRAINT JOURNAL_PARAM_PK PRIMARY KEY 
  (
    PARAMETER_ID, PARAM_NO 
  )
  ENABLE 
);
